version: 2.1

docker_context: &docker_context
  context:
    - Leddzip Dockerhub

develop_filter: &develop_filter
  filters:
    branches:
      only: develop
master_filter: &master_filter
  filters:
    branches:
      only: master

jobs:
  build:
    machine: true
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run: |
          echo test
          echo <<parameters.env>>
          docker --version
          make --version
      - run: |
          echo tester
          echo <<parameters.env>>
      - run: |
          source args
          envsubst "`printf '${%s} ' $(cat args | cut -d' ' -f2 | cut -d'=' -f1)`" < template.dockerfile > Dockerfile
      - run: |
          ls
          cat Dockerfile

workflows:
  "Build develop":
    jobs:
      - build:
          <<: *docker_context
          <<: *develop_filter
          env: dev


